modLoader="javafml"
loaderVersion="[36,)"
license="The MIT License"
[[mods]]
modId="calcium"
version="${file.jarVersion}"
displayName="Calcium"
#updateJSONURL=""
displayURL="https://git.karmakrafts.dev/kk/mc-mods/calcium"
logoFile="calcium.png"
credits="Thanks to covers1624 for helping out with the CCL side of things <3"
authors="KitsuneAlex"
description='''
A compatibility patch between CodeChickenLib and Magnesium/Halogen.
'''
[[dependencies.calcium]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.calcium]]
    modId="minecraft"
    versionRange="[1.16.5]"
    mandatory=true
    ordering="NONE"
    side="BOTH"